# dynamic.yml - dynamic Traefik routes
http:
  routers:
    wazuh-dashboard:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - websecure
      service: wazuh-dashboard
      tls:
        # Explicitly we use the self-signed cert & key instead of Let's Encrypt
        certResolver: ""     # disable ACME
        domains: []
        options: default
        # Use mounted certs
        certificates:
          - certFile: /certs/cert.pem
            keyFile: /certs/key.pem

  services:
    wazuh-dashboard:
      loadBalancer:
        servers:
          - url: "http://wazuh-dashboard:5601"
