# traefik.yml - static Traefik config
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-public   # attach to the swarm overlay network

log:
  level: INFO

accessLog: {}
