---
- name: Ensure secrets are available as facts
  set_fact:
    wazuh_user: "{{ wazuh_user }}"
    wazuh_password: "{{ wazuh_password }}"
    wazuh_api_key: "{{ wazuh_api_key }}"
    tls_private_key: "{{ tls_private_key }}"
    tls_certificate: "{{ tls_certificate }}"
