# Run only on the dashboard (Swarm manager) – secrets are cluster-scoped once created
- name: Build secrets payload map (in-memory only)
  no_log: true
  set_fact:
    _swarm_secrets: >-
      {{
        {
          secret_names.wazuh_api_user: wazuh_user,
          secret_names.wazuh_api_password: wazuh_password,
          secret_names.dashboard_tls_key: traefik_private_key,
          secret_names.dashboard_tls_crt: traefik_certificate
        }
      }}
  when: hostvars[inventory_hostname].role == "dashboard"

# Ensure Swarm secrets exist (create if missing)
- name: "Ensure Swarm secrets exist"
  no_log: true
  docker_secret:
    name: "{{ item.key }}"
    state: present
    data: "{{ item.value }}"
  loop: "{{ _swarm_secrets|dict2items }}"
  when: hostvars[inventory_hostname].role == "dashboard"
