# Tasks for deploying Traefik in Docker Swarm

- name: Create Traefik overlay network
  docker_network:
    name: "{{ traefik_network }}"
    driver: overlay
    scope: swarm
  when: hostvars[inventory_hostname].role == "dashboard"

- name: Ensure Traefik config directory exists
  file:
    path: /etc/traefik
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: hostvars[inventory_hostname].role == "dashboard"

- name: Copy Traefik static config
  copy:
    src: "{{ traefik_static_src }}"
    dest: "{{ traefik_static_file }}"
    owner: root
    group: root
    mode: '0644'
  when: hostvars[inventory_hostname].role == "dashboard"

- name: Copy Traefik dynamic config
  copy:
    src: "{{ traefik_dynamic_src }}"
    dest: "{{ traefik_dynamic_file }}"
    owner: root
    group: root
    mode: '0644'
  when: hostvars[inventory_hostname].role == "dashboard"

- name: Ensure certs directory exists
  file:
    path: /etc/traefik/certs
    state: directory
    owner: root
    group: root
    mode: '0700'
  when: hostvars[inventory_hostname].role == "dashboard"

- name: Deploy TLS certificate (from Ansible Vault)
  copy:
    content: "{{ traefik_certificate }}"
    dest: "{{ traefik_cert_file }}"
    owner: root
    group: root
    mode: '0600'
  when: hostvars[inventory_hostname].role == "dashboard"

- name: Deploy TLS private key (from Ansible Vault)
  copy:
    content: "{{ traefik_private_key }}"
    dest: "{{ traefik_key_file }}"
    owner: root
    group: root
    mode: '0600'
  when: hostvars[inventory_hostname].role == "dashboard"

- name: Deploy Traefik Swarm service
  docker_swarm_service:
    name: traefik
    image: traefik:latest
    publish:
      - published_port: 80
        target_port: 80
      - published_port: 443
        target_port: 443
    constraints:
      - node.role == manager
    networks:
      - name: "{{ traefik_network }}"
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
      - source: "{{ traefik_static_file }}"
        target: /etc/traefik/traefik.yml
        type: bind
      - source: "{{ traefik_dynamic_file }}"
        target: /etc/traefik/dynamic.yml
        type: bind
      - source: "{{ traefik_cert_file }}"
        target: /certs/cert.pem
        type: bind
      - source: "{{ traefik_key_file }}"
        target: /certs/key.pem
        type: bind
  when: hostvars[inventory_hostname].role == "dashboard"
