nodes:
  indexer:
    - name: wazuh-indexer
      ip: 10.0.2.51

  server:
    - name: wazuh-manager
      ip: 10.0.2.51    # single manager, no node_type needed

  dashboard:
    - name: wazuh-dashboard
      ip: 10.0.1.191
