- name: Deploy Wazuh stack on Swarm manager
  block:

    # Render the Jinja2 Docker Compose template to a temporary file
    - name: Render Docker Compose template for Wazuh stack
      template:
        src: docker-compose.yml.j2
        dest: /tmp/docker-compose.yml
      when: hostvars[inventory_hostname].role == "dashboard"

    # Deploy or update the Wazuh stack using the rendered Compose file
    - name: Deploy or update Wazuh stack
      docker_stack:
        name: "{{ swarm_stack_name }}"
        state: present
        compose:
          - /tmp/docker-compose.yml
        prune: true
      when: hostvars[inventory_hostname].role == "dashboard"
      register: deploy_result
      ignore_errors: true   # <-- allow rescue block to handle failure

  rescue:
    - name: Rollback and fail if stack deployment failed
      block:
        - docker_stack:
            name: "{{ swarm_stack_name }}"
            state: absent
        - fail:
            msg: |
              Wazuh stack deployment failed on {{ inventory_hostname }}.
              Docker Stack error output:
              {{ deploy_result.stderr }}  # <-- display detailed error

  always:
    # Cleanup temporary rendered file
    - name: Remove temporary Docker Compose file
      file:
        path: /tmp/docker-compose.yml
        state: absent
      when: hostvars[inventory_hostname].role == "dashboard"
