all:
  children:
    nodes:
      hosts:
        node1:   # Dashboard node (also Swarm manager)
          ansible_host: 10.0.1.44
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/mini-soc.pem
          role: dashboard   # custom variable to indicate role

        node2:   # Manager/indexer node
          ansible_host: 10.0.2.30
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/mini-soc.pem
          role: manager
          run_indexer: true
