# deploy.yml

# Ensure Docker is installed or updated on all nodes
- name: Ensure Docker is installed or updated
  hosts: all
  become: true  # Run tasks with sudo privileges
  gather_facts: true
  tasks:
    - name: Check if Docker is installed
      ansible.builtin.shell: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Update apt cache and upgrade packages if Docker is installed
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
      when: docker_installed.rc == 0

    - name: Install prerequisite packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - aptitude
        state: present
      when: docker_installed.rc != 0

    - name: Create directory for Docker GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      when: docker_installed.rc != 0

    - name: Download and add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true
      when: docker_installed.rc != 0

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
      when: docker_installed.rc != 0

    - name: Install Docker Engine and related packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      when: docker_installed.rc != 0

    - name: Install Python Docker module
      ansible.builtin.pip:
        name: docker
        executable: pip3
      when: docker_installed.rc != 0

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: true

# Log in to GitHub Container Registry
- name: Log in to GitHub Container Registry on Swarm nodes
  hosts: all
  become: true
  tasks:
    - name: Login to GHCR
      docker_login:
        registry_url: ghcr.io
        username: "{{ lookup('env', 'GITHUB_ACTOR') }}"
        password: "{{ lookup('env', 'GHCR_TOKEN') }}"
- name: Deploy Wazuh Stack
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - group_vars/all.yml
    - group_vars/vault.yml    # encrypted
  roles:
    - swarm-init    # initializes swarm and joins other nodes
    - networks      # creates overlay networks
    - secrets       # creates Swarm secrets cluster-wide (on dashboard node)
    - traefik       # deploys Traefik reverse proxy with TLS/ACME
    - deploy-stack  # deploys/updates stack with rollback
