# Initialize Docker Swarm on manager
- name: Initialize Swarm (manager)
  docker_swarm:
    state: present
    advertise_addr: "{{ ansible_host }}"
  when: hostvars[inventory_hostname].role == "dashboard"
  register: swarm_init

# Save join tokens on localhost
- name: Save Swarm join tokens
  set_fact:
    manager_join_token: "{{ swarm_init.swarm_facts.JoinTokens.Manager }}"
    worker_join_token: "{{ swarm_init.swarm_facts.JoinTokens.Worker }}"
  when: hostvars[inventory_hostname].role == "dashboard"
  delegate_to: localhost

# Join worker nodes to the swarm
- name: Join worker nodes to swarm
  docker_swarm:
    state: join
    join_token: "{{ hostvars['node1'].swarm_init.swarm_facts.JoinTokens.Worker }}"
    remote_addrs: ["{{ hostvars['node1'].ansible_host }}"]
  when: hostvars[inventory_hostname].role == "worker"
