- name: Ensure cert directories exist on all nodes
  file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'
  loop:
    - /home/ubuntu/certs/indexer
    - /home/ubuntu/certs/dashboard

- name: Remove existing Wazuh dashboard cert-populate container
  docker_container:
    name: wazuh-certs-populate-dashboard
    state: absent
    force_kill: true
  ignore_errors: true

- name: Remove existing Wazuh indexer cert-populate container
  docker_container:
    name: wazuh-certs-populate-indexer
    state: absent
    force_kill: true
  ignore_errors: true

# ---------------- Sync certs from Node1 to all other nodes ----------------
- name: Sync Wazuh indexer certs to all other nodes
  synchronize:
    src: /home/ubuntu/certs/indexer/
    dest: /home/ubuntu/certs/indexer/
    mode: push
    recursive: true
    rsync_opts:
      - "--rsh='ssh -i /home/ubuntu/.ssh/mini-soc.pem -o StrictHostKeyChecking=no'"
  delegate_to: node1
  run_once: true

- name: Sync Wazuh dashboard certs to all other nodes
  synchronize:
    src: /home/ubuntu/certs/dashboard/
    dest: /home/ubuntu/certs/dashboard/
    mode: push
    recursive: true
    rsync_opts:
      - "--rsh='ssh -i /home/ubuntu/.ssh/mini-soc.pem -o StrictHostKeyChecking=no'"
  delegate_to: node1
  run_once: true


# ---------------- Populate certs into Docker volumes ----------------
- name: Populate Wazuh dashboard certs into Docker volume
  docker_container:
    name: wazuh-certs-populate-dashboard
    image: alpine:latest
    state: started
    command: >
      sh -c "cp -r /source/* /certs/ && chmod -R 644 /certs/* && chown -R 1000:1000 /certs/"
    volumes:
      - "wazuh-certs-dashboard:/certs"
      - "/home/ubuntu/certs/dashboard:/source:ro"
    auto_remove: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['all'] }}"

- name: Populate Wazuh indexer certs into Docker volume
  docker_container:
    name: wazuh-certs-populate-indexer
    image: alpine:latest
    state: started
    command: >
      sh -c "cp -r /source/* /certs/ && chmod -R 644 /certs/* && chown -R 1000:1000 /certs/"
    volumes:
      - "wazuh-certs-indexer:/certs"
      - "/home/ubuntu/certs/indexer:/source:ro"
    auto_remove: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['all'] }}"

# ---------------- Fix ownership and permissions ----------------
- name: Fix ownership and permissions for dashboard certs
  file:
    path: /home/ubuntu/certs/dashboard
    recurse: true
    owner: 1000
    group: 1000
    mode: '0644'
  delegate_to: "{{ item }}"
  loop: "{{ groups['all'] }}"

- name: Fix ownership and permissions for indexer certs
  file:
    path: /home/ubuntu/certs/indexer
    recurse: true
    owner: 1000
    group: 1000
    mode: '0644'
  delegate_to: "{{ item }}"
  loop: "{{ groups['all'] }}"
