---
- name: Ensure cert directories exist on host
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  loop:
    - /home/ubuntu/certs/indexer
    - /home/ubuntu/certs/dashboard

# ---------------- Remove old populate containers ----------------
- name: Remove existing dashboard cert-populate container
  docker_container:
    name: wazuh-certs-populate-dashboard
    state: absent
    force_kill: true
  ignore_errors: true

- name: Remove existing indexer cert-populate container
  docker_container:
    name: wazuh-certs-populate-indexer
    state: absent
    force_kill: true
  ignore_errors: true

# ---------------- Sync indexer certs from node1 ----------------
- name: Sync Wazuh indexer certs from node1 to other nodes
  synchronize:
    src: /home/ubuntu/certs/indexer/
    dest: /home/ubuntu/certs/indexer/
    recursive: true
  delegate_to: node1
  when: inventory_hostname != 'node1'

# ---------------- Populate certs into Docker volumes ----------------
- name: Populate Wazuh certs into Docker volumes
  block:
    - name: Populate dashboard certs into Docker volume
      docker_container:
        name: wazuh-certs-populate-dashboard
        image: alpine:latest
        state: started
        command: >
          sh -c "cp -r /source/* /certs/ && chmod -R 644 /certs/* && chown -R 1000:1000 /certs/"
        volumes:
          - "wazuh-certs-dashboard:/certs"
          - "/home/ubuntu/certs/dashboard:/source:ro"
        auto_remove: true

    - name: Populate indexer certs into Docker volume
      docker_container:
        name: wazuh-certs-populate-indexer
        image: alpine:latest
        state: started
        command: >
          sh -c "cp -r /source/* /certs/ && chmod -R 644 /certs/* && chown -R 1000:1000 /certs/"
        volumes:
          - "wazuh-certs-indexer:/certs"
          - "/home/ubuntu/certs/indexer:/source:ro"
        auto_remove: true
  run_once: false

# ---------------- Fix host cert permissions ----------------
- name: Ensure correct permissions for dashboard certs
  file:
    path: /home/ubuntu/certs/dashboard
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
    recurse: true

- name: Fix file permissions inside dashboard certs dir
  command: find /home/ubuntu/certs/dashboard -type f -exec chmod 0644 {} \;

- name: Ensure correct permissions for indexer certs
  file:
    path: /home/ubuntu/certs/indexer
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
    recurse: true

- name: Fix file permissions inside indexer certs dir
  command: find /home/ubuntu/certs/indexer -type f -exec chmod 0644 {} \;
