- name: Ensure cert directories exist on all nodes
  file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'
  loop:
    - /home/ubuntu/certs/indexer
    - /home/ubuntu/certs/dashboard

- name: Remove any stale Wazuh cert-populate containers
  ansible.builtin.shell: |
    docker rm -f wazuh-certs-populate-dashboard 2>/dev/null || true
    docker rm -f wazuh-certs-populate-indexer 2>/dev/null || true
  delegate_to: "{{ item }}"
  loop: "{{ groups['all'] }}"
  ignore_errors: yes

- name: Populate Wazuh dashboard certs into Docker volume
  docker_container:
    name: wazuh-certs-populate-dashboard
    image: alpine:latest
    state: started
    command: >
      sh -c "cp -r /source/* /certs/ && chmod -R 644 /certs/* && chown -R 1000:1000 /certs/"
    volumes:
      - "wazuh-certs-dashboard:/certs"
      - "/home/ubuntu/certs/dashboard:/source:ro"
    auto_remove: yes
  delegate_to: "{{ item }}"
  loop: "{{ groups['all'] }}"   # Runs on all nodes

- name: Populate Wazuh indexer certs into Docker volume
  docker_container:
    name: wazuh-certs-populate-indexer
    image: alpine:latest
    state: started
    command: >
      sh -c "cp -r /source/* /certs/ && chmod -R 644 /certs/* && chown -R 1000:1000 /certs/"
    volumes:
      - "wazuh-certs-indexer:/certs"
      - "/home/ubuntu/certs/indexer:/source:ro"
    auto_remove: yes
  delegate_to: "{{ item }}"
  loop: "{{ groups['all'] }}"   # Runs on all nodes

- name: Fix ownership and permissions for dashboard certs
  file:
    path: /home/ubuntu/certs/dashboard
    recurse: yes
    owner: 1000
    group: 1000
    mode: '0644'
  delegate_to: "{{ item }}"
  loop: "{{ groups['all'] }}"

- name: Fix ownership and permissions for indexer certs
  file:
    path: /home/ubuntu/certs/indexer
    recurse: yes
    owner: 1000
    group: 1000
    mode: '0644'
  delegate_to: "{{ item }}"
  loop: "{{ groups['all'] }}"
