- name: Ensure cert directories exist on all nodes
  file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'
  loop:
    - /home/ubuntu/certs/indexer
    - /home/ubuntu/certs/dashboard

- name: Remove existing Wazuh dashboard cert-populate container
  docker_container:
    name: wazuh-certs-populate-dashboard
    state: absent
    force_kill: yes
  ignore_errors: yes

- name: Remove existing Wazuh indexer cert-populate container
  docker_container:
    name: wazuh-certs-populate-indexer
    state: absent
    force_kill: yes
  ignore_errors: yes

- name: Sync Wazuh indexer certs to all nodes
  synchronize:
    src: /home/ubuntu/certs/indexer/
    dest: /home/ubuntu/certs/indexer/
    mode: push
    recursive: yes
  delegate_to: node1
  run_once: true
  with_items: "{{ groups['all'] }}"
  loop_control:
    loop_var: target_node

- name: Sync Wazuh dashboard certs to all nodes
  synchronize:
    src: /home/ubuntu/certs/dashboard/
    dest: /home/ubuntu/certs/dashboard/
    mode: push
    recursive: yes
  delegate_to: node1
  run_once: true

- name: Populate Wazuh dashboard certs into Docker volume
  docker_container:
    name: wazuh-certs-populate-dashboard
    image: alpine:latest
    state: started
    command: >
      sh -c "cp -r /source/* /certs/ && chmod -R 644 /certs/* && chown -R 1000:1000 /certs/"
    volumes:
      - "wazuh-certs-dashboard:/certs"
      - "/home/ubuntu/certs/dashboard:/source:ro"
    auto_remove: yes

- name: Populate Wazuh indexer certs into Docker volume
  docker_container:
    name: wazuh-certs-populate-indexer
    image: alpine:latest
    state: started
    command: >
      sh -c "cp -r /source/* /certs/ && chmod -R 644 /certs/* && chown -R 1000:1000 /certs/"
    volumes:
      - "wazuh-certs-indexer:/certs"
      - "/home/ubuntu/certs/indexer:/source:ro"
    auto_remove: yes

- name: Fix ownership and permissions for dashboard certs
  file:
    path: /home/ubuntu/certs/dashboard
    recurse: yes
    owner: 1000
    group: 1000
    mode: '0644'

- name: Fix ownership and permissions for indexer certs
  file:
    path: /home/ubuntu/certs/indexer
    recurse: yes
    owner: 1000
    group: 1000
    mode: '0644'
