- name: Ensure temporary container is removed if it exists
  docker_container:
    name: wazuh-certs-populate
    state: absent
    force_kill: yes

- name: Populate Wazuh certs into Docker volume
  docker_container:
    name: wazuh-certs-populate
    image: alpine:latest
    state: started
    command: >
      sh -c "cp -r /source/* /certs/"
    volumes:
      - "{{ wazuh_certs_volume }}:/certs"
      - "{{ wazuh_certs_source }}:/source:ro"
    auto_remove: yes
